
pod:
 containerName: "container"
 imageName: ""
 containerPort: 80


services:
  name: "service"
  type: NodePort  #due to external IP pending issue, changed from LoadBalancer to NodePort
  app:
   dev: 8089
   uat: 8090
   prod: 8091
  node:
   dev: 30008
   uat: 30018
   prod: 30028

host:
 dev: '30004'
 uat: '30014'
 prod: '30024'

environment: ""

config:
  name: users-app-config
  volume: users-app-config-vol
  mountPath: config
